<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <RootNamespace />
    <PackageId>BookStoreScratch.Installer</PackageId>
    <Version>1.0.0</Version>
    <Authors>allengaodev</Authors>
    <Company>allengaodev</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.VirtualFileSystem" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Embed module definition file -->
    <Content Include="..\..\BookStoreScratch.abpmdl">
      <Pack>true</Pack>
      <PackagePath>content\</PackagePath>
    </Content>

    <!-- Embed package definition files -->
    <Content Include="..\..\**\*.abppkg*">
      <Pack>true</Pack>
      <PackagePath>content\</PackagePath>
    </Content>
  </ItemGroup>
</Project>